language: node_js
node_js: '13'
dist: bionic
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '10.17.0'
    - node_js: '13'
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'PKbZs9sqyC6EK/XKck1XUEK/jAYeM1EAEyyBhaxi3MgPC4wmAyyquSXpEXRPVM5B/inRGh+jYcevL/D+mAHErSuI7dp4LyN1F2hcb2bmCKoToTiDr+3HZb17Y2LgKj0vrQLZ0A41EiriIGNFQhNF+nqCwbadJytqgA0X1jvtbsP5swgsDC57l0MQb+yCKZ20fViyDMHu/mU5VdrJG1svvf/2TUdkTXIgON967Xi98P8Ke8FF1ESBgro4ocq1JAi4UgVZ65EtfpF6zQFG7BYh1JY7lf9CMkhW2Xg7Ub/NiLlSxZ8xOgWjXSYDbwitnfWiKAi2V8KaOYR4lgUbdsmeKHLEugrUfzinMkDi47gl/MYt7BJ1sIycTjY0hbIGy33Cl0QsNShLDI3rQqZ+gY7YlaTdgtYww1S7hKGKwBMQ1klslEw/u6ciKdLkRmMjev+CHOq0VG97bdZSy4Npsi0GDJv2pEVbOGnZeTUNnv5wGY9RSGt0G9LI7GPI6iFSCP5SYAZjAfjifBdOtL1fWK16o8HCtnXimpOT+qvDwmMFL2gOKTst0dqO17WvmvwknZjU4EhdyayK0HzvNAOpgnnafulaby+R3TdZh0GhjUf/UqgIY2bvHmCHnJEoC2bt/CzT+feZC2pPTNbjf8SnfZ4UxOmIxA91iTSfoaRybbX6ioo='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
