language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '10'
    - node_js: '11'
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: "XsiSh9FcbQHORK38jFwKhmsnN2q7RqdTZssTHJhebKF77L1S4LTdwkgpj3dt/3pNj93HOV+/lixjjA6rkh+ERwsVvdk0+V5aGmd/WdMGCw2DcxLYBWCqquwi2LWpzku1zN5B2ypmeYlAZpxn6lY/p1E6F9zQ/KLYZZGtalvcNCndha6I2+vehrH8ZMd1AbdWiXHOXHhyvY2+M9Wfb3H6qsuqC26HtB8VXQ23B1MEndJdwMZPJK6qEglR5/370/+QIz4JCsHJZYx9hyovp9TxlORHGj9vXOceRWIH7PembXnc50lmmHsXlO/vmG2UyoE1I9uvDxNQBJzvknF5Bfk6pyoDP/BsY/FVxT99tf9t8nOp21W1EL8BGPSOUs4u9Ri+Retj95E6jhUuDVAgWFDN0Se+LjCinFMeNCgPsur3AWJ5yLOkrrSxcwI58BrRCvW1wkVCzRK9YC6Onedx/7+ahsU0PFry0+uvWBtdp0pITboDE3kMfV4IUpK6tESE1I40lDaiXZRCqLJAFdK/0RV56I+SvQmQbpjiJvvO/PpUDUBbExEdcHOVwzH1dk61nlAIC9C2vAUY6ZR115Nj0t/phs85gboOoBr5HBxvvOSfwJivyo25bbJLRj5qKjBnIU8/LBJ1Og4JUbL1mm41LhKpX+E7cfxmlmftDQO3ectorgA="
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
